config/routes.rb
Omrails::Application.routes.draw do
  devise_for :users

    get 'about' => 'pages#about'

  root :to => 'pages#Home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def Home
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
		<small>
			<%= link_to "Show Me Your Table Top", "#" %> 
			by <%= link_to "DeVon M.", "#" %> 
		</small>
	</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
 
			<!-- .btn-navbar is used as the toggle for collapsed navbar content -->
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
 
			<!-- Be sure to leave the brand out there if you want it shown -->
			<%= link_to "SMYTT", root_path, class: "brand" %>
 
			<!-- Everything you want hidden at 940px or less, place within here -->
			<div class="nav-collapse collapse">
				<ul class="nav">
					<li class="divider-vertical"></li>
					<li><%= link_to "Home", root_path %></li>
					<li class="divider-vertical"></li>
					<li><%= link_to "About", about_path %></li>
				</ul>
				<ul class="nav pull-right">
					<% if user_signed_in? %>
          	
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            	<% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
				</ul>
				<!-- .nav, .navbar-search, .navbar-form, etc -->
			</div>
 
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>SMYTT</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		
		<div class="container">
			<% flash.each do |name, msg| %>
      	<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
      		<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/pages/Home.html.erb
<div class="hero-unit">
	<h1>Welcome Table Toppers!</h1>
		<p>
			You've found the home page for 
			<%= link_to "Show Me Your Table Top", "#" %> 
			application.
		</p>
	<p>
		<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
	</p>
</div>

app/views/pages/about.html.erb
<h1>About</h1>
	<br>
		<p>
		SMYTT is a project that i'm working that specifically focuses on all the things that go on on your table top. 
		</p>